In [19]:
import pandas as pd
df=pd.read_csv("diabetic.csv")
df.drop("Unnamed: 0",axis=1,inplace=True)
df.drop("Unnamed: 0.1",axis=1,inplace=True)
df.head()

,eye_side,patient_id,level,Image_Path,exists
0,left,18883,0,/home/imran/Downloads/resized/18883_left.jpeg,True
1,left,35406,0,/home/imran/Downloads/resized/35406_left.jpeg,True
2,right,12471,0,/home/imran/Downloads/resized/12471_right.jpeg,True
3,left,16171,0,/home/imran/Downloads/resized/16171_left.jpeg,True
4,left,10897,0,/home/imran/Downloads/resized/10897_left.jpeg,True

In [20]:
import os
df["image"]= df['Image_Path'].map(lambda x: x[30:])
df.head()
path="/home/imran/diabetic/resized/"

df['Image_Path'] = df['image'].map(lambda x: os.path.join(path+x))
df['exists'] = df['Image_Path'].map(os.path.exists)
df.drop("image",axis=1,inplace=True)
df.head()

,eye_side,patient_id,level,Image_Path,exists
0,left,18883,0,/home/imran/diabetic/resized/18883_left.jpeg,True
1,left,35406,0,/home/imran/diabetic/resized/35406_left.jpeg,True
2,right,12471,0,/home/imran/diabetic/resized/12471_right.jpeg,True
3,left,16171,0,/home/imran/diabetic/resized/16171_left.jpeg,True
4,left,10897,0,/home/imran/diabetic/resized/10897_left.jpeg,True

In [21]:
df.to_csv("14kDiabteic.csv")